### ISSUE TITLE
What is the advantage of Rabbitmq's backingqueue mechanism?

### ISSUE THREAD

**Issue by ppLorins** [rabbitmq/internals#17]
BackingQueue is a complicated mechanism , I don't know how does it come out and what's its advantages . I can figure out an easier approach of doing message swapping between RAM and disk , consider this :
 
 ##  preconditions :
 
	* the data structure of messages in RAM is a linked list , like m1->m2->m3 . Each of `mx` is a structure contains meta data(not the content) of the message ,and links to the next `mx`.
	* There is a limit  number of messages in RAM , says 5 . 
 
 ## producing process
 
 
	1. Producer continues pushing messages into the queue ,message sequence is [1,2,3,4,5] , until the queue is filled like  `m5(tail)<-->m4<-->m3<-->m2<-->m1(head)`
	2. Now, reach the limit , swap 1/2 of messages onto the disk ,starting from the tail . Then , m5 and m4's content are no longer in RAM , they are now on the disk .
	3. Push m6 and m7 into the queue. 
	4. Trigger the limit condition, back to step2 ..
 
 
 ## consuming process
 
	1. consuming from m1 to m5 , whenever find a message that its content is on the disk instead of RAM , load the message and its adjacent neighbours  into RAM .
	
	
	
The above way doesn't consider the RAM occupied by the message meta data ( index's counterpart in BackingQueue ) ,  since it could probably be small enough . 
	
	
So , what's the advantages of BackingQueue can bring ?  Not just compared to my way , but also how it comes out?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Background GC has nothing to do with moving messages to disk. GC of binaries in Erlang is lazy and on some workloads benefits from a forced GC for all idle processes, even if all the messages that (a subset of) the binaries belong to have already been moved to disk. That's what background GC does, at dynamically adjusted intervals.
